type User @table {
  name: String!
  bio: String!
  email: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  photoUrl: String
  phoneNumber: String
  linkedInUrl: String
  githubUrl: String
}

type Project @table {
  title: String!
  description: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  owner: User
  projectUrl: String
  githubRepoUrl: String
  imageUrl: String
  technologiesUsed: [String]
}

type Experience @table {
  title: String!
  organization: String!
  startDate: Date!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  owner: User
  endDate: Date
  description: String
  location: String
}

type Skill @table {
  name: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  owner: User
  category: String
}